### ISSUE TITLE
Замечания по СРС 1 по курсу СУБД

### ISSUE THREAD

**Issue by ns-roxer** [go-park-mail-ru/2023_2_potatiki#5]
1. https://github.com/go-park-mail-ru/2023_2_potatiki/blob/stage/db/normalized/relations.md - не хватает краткого описании того, что из себя представляет эта таблица. Другими словами, какие данные в ней лежат с точки зрения бизнес логики всей системы. Описание должно быть лаконичным, без воды. Чтобы можно было быстро прочитать и понять для чего эта таблица в вашем приложении.
2. https://github.com/go-park-mail-ru/2023_2_potatiki/blob/stage/db/normalized/relations.md?plain=1#L63 - исправить опечатки
3. https://github.com/go-park-mail-ru/2023_2_potatiki/blob/955be85ce1c79524bec53c314a7d2790229cc02f/db/normalized/relations.md?plain=1#L4 -  id является суррогатным ключем, указвать его в списке зависимостей нет практического смысла, так как таких суррогатов можно навводить неограниченное количество и все будут одновременно и детерминантами и завивисимыми. Пожалуйста, поправьте такие описания.
4. https://github.com/go-park-mail-ru/2023_2_potatiki/tree/stage/db/migraions - опечатка в названии дирретории
5. почему все идентификаторы сделали UUID типом, а не serial(bigserial)? 
6. переименовать поля в таблице:
    1. name_product -> просто name, не нужно дублировать имя таблицы
    2. все явно заданные имена constraint привести к snake_case регистру
    3. поля с названиями ***_date привести к виду ***_at, так как в типе используется не date, timestamp!
7. Вместо timestamp использовать timestamptz, сразу учимся работать с часовыми поясами. У вас же клон очень масштабного проекта!
8. Вопрос - таблица category_reference какой способ организации иерархической структуры вы попытались организовать? Adjacency List? Почему это вобще отдельная таблица, а не поле parent_category в таблице category?
9. Вопрос - order_info.status - почему не reference на справочную таблицу?
10. Запросы в методах репозитория используют названия колонок в регистре несоответствующем DDL схемы. Необходимо исправить!

**Comment by scremyda** [comment]
Почему все идентификаторы сделали UUID типом, а не serial(bigserial)?

Мы выбрали UUID:
1. Из-за его глобальной уникальности.
2. Из-за отсутствия предсказуемости.
3. Подходит для автономной генерации данных.
4. Совместимость с несколькими хранилищами данных.
5. Рекомендация ментора.

По итогу: Получаем более безопасное, гибкое решение.

**Comment by khristina455** [comment]
1. Добавлены описания к таблицам
2. Исправлены
3. Отношения рассматриваются без учета id
4. Поправлено
6. Переименовано
7. Поменяли
8. Сделали аттрибут parent у таблицы category
9. Вынесли статусы в отдельную таблицу
10. Поправили
